### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by real34** [principalstudio/html-webpack-inject-preload#22]
Hi,

Thanks for this webpack plugin, it is simple and efficient!

I was wondering what license it was released in? (To know if it can be used in a customer context or not). Is it MIT?

Thanks for the information.

**Comment by Applelo** [comment]
The licence is MIT. I will update the plugin with the licence. Sorry for the inconvenience.

**Comment by real34** [comment]
Thank you very much for answering in a timely fashion.

> Sorry for the inconvenience.

There's no need to apologize! There was no inconvenience **at all** :)

Thanks again for sharing this library. :+1:
