### ISSUE TITLE
Update for Webpack 5

### ISSUE THREAD

**Issue by Applelo** [principalstudio/html-webpack-inject-preload#6]
### Problems

- html-webpack plugin https://github.com/jantimon/html-webpack-plugin/issues/1527

**Comment by jantimon** [comment]
html-webpack-plugin@5 is now in beta an will probably be released soon - is there anything I can do to support this issue?

**Comment by Applelo** [comment]
I don't think so, I just need to test with the update of html-webpack-plugin ^^. Thank you to ask and for your incredible project ❤️

**Comment by jantimon** [comment]
If you like you can create a pull request to the html-webpack-plugin and add a link to your plugin to the readme

**Comment by floriankapaun** [comment]
Hey @Applelo, is there a plan to release an update for Webpack 5? If yes, can you say when? Would highly appreciate it! 😁
