### ISSUE TITLE
'@principalstudio/html-webpack-inject-preload@latest' is not in the npm registry

### ISSUE THREAD

**Issue by floriankapaun** [principalstudio/html-webpack-inject-preload#7]
Hey @Applelo it looks like your project could help me out with injecting preload attribute to css files while using webpack 5 and html-webpack-plugin.

Unfortunately, it looks like the package has been removed from [npmjs.com](https://npmjs.com/).

Would you mind making your plugin available again?

**Comment by Applelo** [comment]
Hello, this plugin was not available through npm registry because we use it for internal use ^^. However, yes I can make it available on npmjs :)

**Comment by Applelo** [comment]
The plugin is now available on NPM : https://www.npmjs.com/package/@principalstudio/html-webpack-inject-preload
